### ISSUE TITLE
Proxy Deposits

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#184]
It's often the case that the person who does the upload is not the person who actually has the legal rights to agree to the terms of the Deposit Agreement. An example is when a curator or research assistant uploads a dataset on behalf of a researcher.

The distinction between the rights-holding *depositor* and the *proxy* who performs the deposit should be reflected in ScholarSphere's abstractions. Some approaches: 

#### `depositor` is just a metadata field; it can be set as needed by admins after the deposit. 

- Pros: That's how it works now; Technically simple.
- Cons: Requires curators to manually fix records; no record of the depositor agreeing to the deposit agreement. 

#### "Authorized Proxies" can create works on other's behalf

- Pros: Feature exists in ScholarSphere 3, though unclear how much it's used. 
- Cons: Authorization should be revoked later; no record of the depositor agreeing to the deposit agreement. 

#### Proxy (or anyone) can set alternate depositor but that person needs to agree to the Deposit Agreement to complete the deposit. 

- Pros: record of the depositor agreeing to the deposit agreement
- Cons: complicates the deposit process and requires intervention from depositor.

**Comment by awead** [comment]
There are data model implications with the above scenarios. Currently, in Scholarsphere 4, the depositor is the user record created when that user logs into Scholarsphere. Any works created are linked to that record. The concept of a proxy would complicate this model somewhat because the works created by the proxy would be linked to the proxy and not the user record considered to be the depositor. Furthermore, the depositor might not even be an actual user of Scholarsphere.

I think the above features should be implemented with certain data model changes. Such as:
* removing the explicit linkage between User and Work models
* re-defining User as an entity solely concerned with authorization within the application
* model depositors and proxies in their own way
    * either extend Creator to model this information; or, create a new entities such as Depositor and Proxy
    * possibly rename Creator to Agent to evoke agent-as-creator and agent-as-depositor polymorphism
* discuss other ideas

**Comment by DanCoughlin** [comment]
Migrate over the proxy deposit id which is the user. We have database changes, but when we create the proxy user then we need an actor record and need to make sure those are linked up. 

We will not infer proxy deposits that are not explicit in the metadata.

**Comment by awead** [comment]
## Update

This issue only affects a very few number of works. There are only 61 works that have a proxy or "on behalf of" field in them. Of those, the majority of them all list the same user for depositor, proxy, and on behalf of.

Of those, there are only two that identify a proxy (i.e. `proxy_depositor_ssim`) different from the depositor:

sj139194f
4f4752g50f

And one that identifies an "on behalf of" user:

9306sz402

The impact of this is when the work migrated to Scholarsphere 4, only the _depositor's_ information will be migrated. If we want to add the proxy information, we could add it _manually_. In the case of the "on behalf of" user, it's impossible to tell which user is the actual depositor because there is not proxy listed, and neither the listed depositor nor the "on behalf of" user are one of the creators.

**Comment by awead** [comment]
This will be fixed in #622
