### ISSUE TITLE
Collections Model

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#255]
We need to develop the model for collections, whether a collection belongs to a work or vice versa, seemed to decide on:

-  a Many-to-Many join table for holding relationships
- need a place holder for order (although we are not storing order for works in a collection at this point) 
- Works can exist in multiple collections

**Comment by srerickson** [comment]
After comparing the "additional fields" of Collections and Works in SS3, I think it's safe to remove the `rights` field from Collections in SS4: it's not used and it's irrelevant because `rights` is required for all the Works in the Collection. There are other fields that might be removed for lack of use (or very minimal use) but in the spirit of minimizing model changes from SS3, let's migrate them for now and maybe cut later.
