### ISSUE TITLE
Clam AV jobs

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#258]
We want to run virus scanning on a file once uploaded and either approve the file or mark it and notify appropriately.

**Comment by whereismyjetpack** [comment]
Created a branch that has a working implementation of queuing up a job from scholarsphere, and then having another process pick up the job. in this case we're calling it "clam-listener"

https://github.com/psu-stewardship/scholarsphere-4/tree/preview/clam-job

This probably isn't where these jobs should get kicked off from, I wasn't sure where in the work / workversion controller things should go. we also probably want to pass more than just `file_data` hash to the listener, we might want to provide some metadata (url to the work, etc) so that when clamav detects a virus we can include it in the message that gets sent out

**Comment by awead** [comment]
Fixed in #372
