### ISSUE TITLE
Default Ordering Works in a Collection

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#275]
We will have a default order for a collection exposed in the UI, not able to be manipulated (at this point) on the front end, but allow researchers to see what the order will be when displayed.

**Comment by srerickson** [comment]
The only ask here is that the default order of works in a collection should be based (primarily) on the value in the "position" column---that's really it. (Note, I suppose it's not even necessary to actually set the position for the new entries in the collection, so long as the position *would be* respected if it were set).

This ticket is scoped very precisely because it (sort of) covers functionality that is not already present in SS3, which is taboo at this point in the development of SS4. If it might take longer than 30 mins, we will hold for v. 4.1.
