### ISSUE TITLE
Can't Mint DOI in draft state

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#591]
Only mint a DOI on a published work

**Comment by rschenk** [comment]
The DOI is actually minting correctly. The cause of this bug is the following:

```ruby
class Work < ApplicationRecord
  
  def count_view!
    raise ArgumentError, 'work must have a published version' if latest_published_version.nil?  # 👈 this

    latest_published_version.count_view!
  end

end
```


What happens is the following:

Given: 
1. Only Works can have DOIs, not Versions

When:
1. I create a Work that only has a single, unpublished draft version
2. And I go to its resource page: `GET /resources/:draft-version-uuid`
3. And I click the button to mint a doi: `POST /dois/:parent-work-uuid` (see Given 1)
4. The DOI mints correctly

Then:
1. The DoisController, given the parent Work's uuid (see When 3), will redirect back to the parent Work's resource page: '/resources/:parent-work-uuid`
2. The view analytics code in `Work#count_view!` raises an ArgumentError

We should definitely fix Work#count_view! to simply do nothing if there is not a published work, rather than raise an Exception (OR we should catch that exception in the controller code). Doing so would fix this problem.

However, we should perhaps consider what the DoisController is doing as well. One thing we could do is redirect back to the calling page, rather than redirecting to the Work resource page explicitly. Redirecting back to the calling page is not always guaranteed to work (it relies on the Referrer header to be present in the HTTP request), but 80% of the time it works every time, and we can provide a fallback. 

![talkamongstyourselves](https://user-images.githubusercontent.com/14730/96629605-d2e38600-12e1-11eb-85e1-80e65ee8956e.jpg)

**Comment by rschenk** [comment]
@awead ☝️
